"""Token usage and cost tracking per agent run.

Provides :class:`CostTracker` to record per-call token usage and
estimated cost, plus helpers to print a rich run summary and persist
it to disk as ``summary.json``.
"""

from __future__ import annotations

import json
import sys
from collections import Counter
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from agent_forge.agent.models import AgentRun
    from agent_forge.llm.base import TokenUsage

# ---------------------------------------------------------------------------
# Model pricing — loaded from vendored LiteLLM snapshot
# ---------------------------------------------------------------------------
# Prices are **per token** (not per 1M).  The vendored file is generated by
# ``scripts/update_prices.py`` which fetches the community-maintained
# LiteLLM pricing database.  Run ``make update-prices`` to refresh.
#
# Fallback defaults are used when the vendored file is missing.

_PRICES_FILE = Path(__file__).with_name("model_prices.json")

# Hardcoded fallback (per token) — used only if model_prices.json is absent
_FALLBACK_PRICES: dict[str, dict[str, float]] = {
    "gemini-2.0-flash": {
        "input_cost_per_token": 1e-07,
        "output_cost_per_token": 4e-07,
    },
    "gemini-3.1-flash-lite-preview": {
        "input_cost_per_token": 2.5e-07,
        "output_cost_per_token": 1.5e-06,
    },
    "gpt-4o": {
        "input_cost_per_token": 2.5e-06,
        "output_cost_per_token": 1e-05,
    },
    "gpt-5.4": {
        "input_cost_per_token": 2.5e-06,
        "output_cost_per_token": 1.5e-05,
    },
    "claude-sonnet-4-20250514": {
        "input_cost_per_token": 3e-06,
        "output_cost_per_token": 1.5e-05,
    },
    "claude-sonnet-4-6": {
        "input_cost_per_token": 3e-06,
        "output_cost_per_token": 1.5e-05,
    },
    "claude-opus-4-6": {
        "input_cost_per_token": 5e-06,
        "output_cost_per_token": 2.5e-05,
    },
}


def _load_prices() -> dict[str, dict[str, float]]:
    """Load pricing from vendored file, falling back to hardcoded defaults."""
    if _PRICES_FILE.exists():
        try:
            return json.loads(_PRICES_FILE.read_text())  # type: ignore[no-any-return]
        except (json.JSONDecodeError, OSError):
            pass
    return dict(_FALLBACK_PRICES)


COST_TABLE: dict[str, dict[str, float]] = _load_prices()

# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------


@dataclass
class CostEntry:
    """Record of token usage and estimated cost for a single LLM call."""

    model: str
    prompt_tokens: int
    completion_tokens: int
    estimated_cost_usd: float
    timestamp: datetime = field(default_factory=lambda: datetime.now(UTC))


@dataclass
class CostTracker:
    """Tracks token usage and estimated cost across an entire agent run."""

    run_id: str
    entries: list[CostEntry] = field(default_factory=list)

    # -- Recording ---------------------------------------------------------

    def record(self, usage: TokenUsage, model: str) -> None:
        """Append a cost entry for one LLM call."""
        cost = _estimate_cost(usage, model)
        self.entries.append(
            CostEntry(
                model=model,
                prompt_tokens=usage.prompt_tokens,
                completion_tokens=usage.completion_tokens,
                estimated_cost_usd=cost,
            )
        )

    # -- Aggregation -------------------------------------------------------

    def total_cost(self) -> float:
        """Sum of estimated costs across all recorded calls."""
        return sum(e.estimated_cost_usd for e in self.entries)

    def summary(self) -> dict[str, Any]:
        """Return an aggregated summary dict."""
        return {
            "run_id": self.run_id,
            "total_prompt_tokens": sum(e.prompt_tokens for e in self.entries),
            "total_completion_tokens": sum(
                e.completion_tokens for e in self.entries
            ),
            "total_tokens": sum(
                e.prompt_tokens + e.completion_tokens for e in self.entries
            ),
            "total_cost_usd": self.total_cost(),
            "llm_calls": len(self.entries),
        }


# ---------------------------------------------------------------------------
# Cost estimation helper
# ---------------------------------------------------------------------------


def _estimate_cost(usage: TokenUsage, model: str) -> float:
    """Compute estimated USD cost for a single LLM call.

    Pricing is **per token** (sourced from LiteLLM's community database).
    """
    pricing = COST_TABLE.get(model)
    if pricing is None:
        return 0.0
    prompt_cost = usage.prompt_tokens * pricing["input_cost_per_token"]
    completion_cost = usage.completion_tokens * pricing["output_cost_per_token"]
    return prompt_cost + completion_cost


# ---------------------------------------------------------------------------
# Run summary — rich box-drawn console output
# ---------------------------------------------------------------------------

_STATUS_ICONS: dict[str, str] = {
    "completed": "✅ COMPLETED",
    "failed": "❌ FAILED",
    "timeout": "⏱️  TIMEOUT",
    "cancelled": "🚫 CANCELLED",
    "running": "🔄 RUNNING",
    "pending": "⏳ PENDING",
}

_BOX_WIDTH = 58


def _row(label: str, value: str) -> str:
    """Format a single row: ║ label  value  ║."""
    inner = f" {label:<16}{value}"
    return f"║{inner:<{_BOX_WIDTH}}║"


def _section_header(title: str) -> str:
    """Format a section separator with title."""
    return f"╠{'─' * _BOX_WIDTH}╣\n║ {title:<{_BOX_WIDTH - 1}}║"


def _tool_summary_lines(run: AgentRun) -> list[str]:
    """Build the 'Tool Invocations' section lines."""
    if not run.tool_invocations:
        return []
    lines = [_section_header("Tool Invocations")]
    tool_counts: Counter[str] = Counter()
    tool_times: dict[str, list[int]] = {}
    for inv in run.tool_invocations:
        tool_counts[inv.tool_name] += 1
        tool_times.setdefault(inv.tool_name, []).append(inv.duration_ms)
    for name, count in tool_counts.most_common():
        avg_ms = sum(tool_times[name]) // len(tool_times[name])
        call_word = "call" if count == 1 else "calls"
        lines.append(_row(f"  {name}:", f"{count} {call_word} (avg {avg_ms:,}ms)"))
    return lines


def _modified_files_lines(run: AgentRun) -> list[str]:
    """Build the 'Files Modified' section lines."""
    modified: list[str] = []
    for inv in run.tool_invocations:
        if inv.tool_name in ("write_file", "edit_file") and not inv.result.error:
            path = inv.arguments.get("path") or inv.arguments.get("file_path")
            if isinstance(path, str) and path not in modified:
                modified.append(path)
    if not modified:
        return []
    lines = [_section_header("Files Modified")]
    for fpath in modified:
        lines.append(_row("  M", fpath))
    return lines


def print_run_summary(
    run: AgentRun,
    tracker: CostTracker,
    *,
    file: Any = None,
) -> str:
    """Print a box-drawn run summary to *file* (default: stderr).

    Returns the formatted summary string.
    """
    if file is None:
        file = sys.stderr

    s = tracker.summary()
    status_str = _STATUS_ICONS.get(run.state.value, run.state.value.upper())
    duration = "N/A"
    if run.completed_at and run.created_at:
        dur_secs = (run.completed_at - run.created_at).total_seconds()
        duration = f"{dur_secs:.1f}s"

    # Truncate task to fit the box
    task_display = run.task[:38] + "…" if len(run.task) > 39 else run.task

    lines: list[str] = [
        f"╔{'═' * _BOX_WIDTH}╗",
        f"║{'Agent Forge — Run Summary':^{_BOX_WIDTH}}║",
        f"╠{'═' * _BOX_WIDTH}╣",
        _row("Run ID:", run.id),
        _row("Status:", status_str),
        _row("Task:", task_display),
        _row("Duration:", duration),
        _row("Iterations:", str(run.iterations)),
        _row("Model:", run.config.model),
        # Token usage
        _section_header("Token Usage"),
        _row("  Prompt:", f"{s['total_prompt_tokens']:,} tokens"),
        _row("  Completion:", f"{s['total_completion_tokens']:,} tokens"),
        _row("  Total:", f"{s['total_tokens']:,} tokens"),
        _row("  Est. Cost:", f"${s['total_cost_usd']:.4f}"),
    ]

    lines.extend(_tool_summary_lines(run))
    lines.extend(_modified_files_lines(run))
    lines.append(f"╚{'═' * _BOX_WIDTH}╝")

    output = "\n".join(lines)
    print(output, file=file)
    return output


# ---------------------------------------------------------------------------
# Persist summary.json
# ---------------------------------------------------------------------------


def save_summary(
    run: AgentRun,
    tracker: CostTracker,
    *,
    base_dir: Path | str | None = None,
) -> Path:
    """Write ``summary.json`` under the run's directory.

    Returns the path to the written file.
    """
    from agent_forge.config import USER_CONFIG_DIR

    runs_dir = Path(base_dir) if base_dir is not None else USER_CONFIG_DIR / "runs"
    run_dir = runs_dir / run.id
    run_dir.mkdir(parents=True, exist_ok=True)

    duration = None
    if run.completed_at and run.created_at:
        duration = (run.completed_at - run.created_at).total_seconds()

    s = tracker.summary()

    summary_data: dict[str, Any] = {
        "run_id": run.id,
        "state": run.state.value,
        "task": run.task,
        "model": run.config.model,
        "duration_seconds": duration,
        "iterations": run.iterations,
        "tokens": {
            "prompt": s["total_prompt_tokens"],
            "completion": s["total_completion_tokens"],
            "total": s["total_tokens"],
        },
        "estimated_cost_usd": s["total_cost_usd"],
        "llm_calls": s["llm_calls"],
        "tool_invocations": len(run.tool_invocations),
        "created_at": run.created_at.isoformat(),
        "completed_at": run.completed_at.isoformat() if run.completed_at else None,
    }

    summary_path = run_dir / "summary.json"
    summary_path.write_text(json.dumps(summary_data, indent=2) + "\n")
    return summary_path
